import 'package:flutter/material.dart';
import '../settings/farm_location_settings.dart';
import '../theme/app_theme.dart';

Future<void> showFarmLocationPicker(BuildContext context) async {
  await Navigator.of(context).push(MaterialPageRoute(builder: (_) => const FarmLocationPickerPage()));
}

class FarmLocationPickerPage extends StatefulWidget {
  const FarmLocationPickerPage({super.key});
  @override State<FarmLocationPickerPage> createState()=>_FarmLocationPickerPageState();
}

class _FarmLocationPickerPageState extends State<FarmLocationPickerPage>{
  late String province,city,town;
  static const _towns=<String,List<String>>{
    '경상북도|김천시':['아포읍','농소면','남면','개령면','감문면','어모면','봉산면','대항면','감천면','조마면','구성면','지례면','부항면','대덕면','증산면'],
  };
  @override void initState(){super.initState();final x=FarmLocationSettings.instance.location;province=x.province;city=x.cityCounty;town=x.town;}
  List<String> get townList=>_towns['$province|$city']??(town.isEmpty?const[]:[town]);
  Future<void> _save()async{final base=FarmLocationSettings.locations[province]!.firstWhere((x)=>x.cityCounty==city);await FarmLocationSettings.instance.setLocation(FarmLocation(province:province,cityCounty:city,town:town,latitude:base.latitude,longitude:base.longitude));if(mounted)Navigator.pop(context);}
  @override Widget build(BuildContext context){final cities=FarmLocationSettings.locations[province]!;return Scaffold(backgroundColor:AppColors.background,appBar:AppBar(toolbarHeight:70,backgroundColor:Colors.transparent,centerTitle:true,leading:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_ios_new_rounded)),title:const Column(children:[Text('지역 지원사업',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),SizedBox(height:2),Text('지자체 공식 공고를 한곳에서 확인하세요.',style:TextStyle(fontSize:10.5,color:AppColors.secondary,fontWeight:FontWeight.w600))])),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(14,5,14,26),children:[
    _locationHero(),const SizedBox(height:12),_serviceTabs(),const SizedBox(height:14),Container(padding:const EdgeInsets.all(14),decoration:appCard(radius:22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
      const Text('지역 선택',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('농장 소재지와 같은 지역을 선택하면\n해당 지역의 지원사업·날씨·질병 정보를 확인할 수 있습니다.',style:TextStyle(fontSize:11.5,height:1.55,color:AppColors.secondary,fontWeight:FontWeight.w600)),const SizedBox(height:12),
      SizedBox(height:42,child:ListView(scrollDirection:Axis.horizontal,children:FarmLocationSettings.locations.keys.map((x)=>Padding(padding:const EdgeInsets.only(right:7),child:_provinceChip(x))).toList())),const SizedBox(height:12),
      SizedBox(height:430,child:Row(children:[Expanded(child:_areaColumn('시·군',cities.map((x)=>x.cityCounty).toList(),city,(x)=>setState((){city=x;town='';}))),const SizedBox(width:6),Expanded(child:_areaColumn('읍·면·동',townList,town,(x)=>setState(()=>town=x),empty:'세부 지역은\nGPS 연동 시\n자동 설정')),const SizedBox(width:6),Expanded(child:_result())])),const SizedBox(height:14),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:_save,style:FilledButton.styleFrom(backgroundColor:AppColors.coral,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))),child:const Text('이 지역으로 설정하기  ›',style:TextStyle(fontSize:15,fontWeight:FontWeight.w900))))
    ])),const SizedBox(height:12),_notice()
  ])));
  }
  Widget _locationHero()=>Container(height:98,padding:const EdgeInsets.symmetric(horizontal:16),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFFF7F9),Color(0xFFFFEAF0)]),borderRadius:BorderRadius.circular(22),border:Border.all(color:const Color(0xFFFFE1E9))),child:Row(children:[const CircleAvatar(radius:25,backgroundColor:Colors.white,child:Icon(Icons.location_on_rounded,size:31,color:AppColors.coral)),const SizedBox(width:12),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('선택 지역',style:TextStyle(fontSize:10,color:AppColors.secondary,fontWeight:FontWeight.w700)),const SizedBox(height:2),Text([province,city,town].where((x)=>x.isNotEmpty).join(' '),overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900))])),const Text('🐷',style:TextStyle(fontSize:39)),const Icon(Icons.campaign_rounded,color:AppColors.coral,size:30)]));
  Widget _serviceTabs(){const rows=[('지역 선택',Icons.location_on_rounded),('날씨',Icons.wb_sunny_outlined),('주변 질병',Icons.coronavirus_outlined),('지원사업',Icons.article_outlined)];return Row(children:rows.indexed.map((entry){final selected=entry.$1==0,x=entry.$2;return Expanded(child:Container(height:62,margin:const EdgeInsets.symmetric(horizontal:3),decoration:BoxDecoration(color:selected?AppColors.coral:Colors.white,borderRadius:BorderRadius.circular(13),boxShadow:const [BoxShadow(color:Color(0x0B000000),blurRadius:9,offset:Offset(0,3))]),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(x.$2,size:24,color:selected?Colors.white:const Color(0xFF81505C)),const SizedBox(height:2),Text(x.$1,style:TextStyle(fontSize:10.5,fontWeight:FontWeight.w800,color:selected?Colors.white:AppColors.text))])));}).toList());}
  Widget _provinceChip(String x){final selected=x==province;return InkWell(onTap:()=>setState((){province=x;city=FarmLocationSettings.locations[x]!.first.cityCounty;town='';}),borderRadius:BorderRadius.circular(11),child:Container(padding:const EdgeInsets.symmetric(horizontal:15),alignment:Alignment.center,decoration:BoxDecoration(color:selected?AppColors.coral:const Color(0xFFFFF6F8),borderRadius:BorderRadius.circular(11),border:Border.all(color:selected?AppColors.coral:AppColors.divider)),child:Text(x,style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:selected?Colors.white:AppColors.text))));}
  Widget _areaColumn(String title,List<String> rows,String selected,ValueChanged<String> onTap,{String? empty})=>Container(decoration:BoxDecoration(border:Border.all(color:AppColors.divider),borderRadius:BorderRadius.circular(12)),clipBehavior:Clip.antiAlias,child:Column(children:[Container(height:40,color:const Color(0xFFFFF4F7),alignment:Alignment.centerLeft,padding:const EdgeInsets.symmetric(horizontal:9),child:Text('⌖  $title',style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900))),Expanded(child:rows.isEmpty?Center(child:Text(empty??'정보 없음',textAlign:TextAlign.center,style:const TextStyle(fontSize:10,height:1.5,color:AppColors.secondary))):ListView(children:rows.map((x)=>InkWell(onTap:()=>onTap(x),child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:9),color:x==selected?AppColors.lightCoral:null,child:Row(children:[Expanded(child:Text(x,style:TextStyle(fontSize:11,fontWeight:x==selected?FontWeight.w900:FontWeight.w600,color:x==selected?AppColors.coral:AppColors.text))),if(x==selected)const Icon(Icons.check_rounded,size:16,color:AppColors.coral)]))).toList()))]));
  Widget _result()=>Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(border:Border.all(color:AppColors.divider),borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('⌖  선택 결과',style:TextStyle(fontSize:11,fontWeight:FontWeight.w900)),const SizedBox(height:18),Text('$province > $city',style:const TextStyle(fontSize:9.5,height:1.4,color:AppColors.secondary)),const SizedBox(height:7),Text(town.isEmpty?city:town,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900))]));
  Widget _notice()=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFFFFF1F5),borderRadius:BorderRadius.circular(18)),child:const Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.lightbulb_rounded,color:AppColors.coral),SizedBox(width:10),Expanded(child:Text('안내\n선택한 지역의 공식 지원사업·날씨·주변 질병 정보를 제공합니다.\n임의의 사업이나 지원금액은 표시하지 않습니다.',style:TextStyle(fontSize:10.5,height:1.5,fontWeight:FontWeight.w600)))]));
}
