import 'package:flutter/material.dart';
import '../models/weather_farm_models.dart';
import '../theme/app_theme.dart';

class WeatherSummaryCard extends StatelessWidget {
  const WeatherSummaryCard({super.key,required this.guide,required this.onTap});
  final WeatherFarmGuide guide;final VoidCallback onTap;
  @override Widget build(BuildContext context)=>Material(color:AppColors.lightBlue,borderRadius:BorderRadius.circular(18),child:InkWell(key:const ValueKey('weather_farm_guide'),onTap:onTap,borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Stack(children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('🌤️',style:TextStyle(fontSize:27)),const SizedBox(width:5),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('오늘 날씨',style:TextStyle(fontSize:15,fontWeight:FontWeight.w900)),FittedBox(fit:BoxFit.scaleDown,alignment:Alignment.centerLeft,child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('${guide.tempMax.toStringAsFixed(0)}°C',style:const TextStyle(fontSize:27,height:1,fontWeight:FontWeight.w900)),const SizedBox(width:3),Padding(padding:const EdgeInsets.only(bottom:2),child:Text(guide.condition,style:const TextStyle(fontSize:8)))]) )]))]),Positioned(right:0,top:0,child:Row(children:[const Icon(Icons.location_on,color:AppColors.blue,size:12),Text(guide.region,style:const TextStyle(fontSize:7,color:AppColors.secondary))]))]),
    const SizedBox(height:8),Text('최고 ${guide.tempMax.toStringAsFixed(0)}°  |  최저 ${guide.tempMin.toStringAsFixed(0)}°',style:const TextStyle(fontSize:10,color:AppColors.secondary)),const SizedBox(height:8),Container(padding:const EdgeInsets.symmetric(horizontal:5,vertical:7),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(10)),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[_WeatherFact(Icons.water_drop,'습도','${guide.humidity.toStringAsFixed(0)}%'),_WeatherFact(Icons.umbrella,'강수','${guide.rainProbability.toStringAsFixed(0)}%'),_WeatherFact(Icons.thermostat,'일교차','${guide.diurnalRange.toStringAsFixed(0)}°')])),const Spacer(),Container(width:double.infinity,padding:const EdgeInsets.all(7),decoration:BoxDecoration(color:AppColors.lightCoral,borderRadius:BorderRadius.circular(10)),child:Row(children:[const Icon(Icons.health_and_safety_outlined,color:AppColors.coral,size:16),const SizedBox(width:5),Expanded(child:Text(guide.checks.isEmpty?'오늘의 건강·환기 점검을 확인하세요.':guide.checks.first,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:7.5,height:1.3,color:AppColors.coral,fontWeight:FontWeight.w700))),const Icon(Icons.chevron_right,color:AppColors.coral,size:15)])),
  ]))));
}
class _WeatherFact extends StatelessWidget {const _WeatherFact(this.icon,this.label,this.value);final IconData icon;final String label,value;@override Widget build(BuildContext context)=>Column(children:[Icon(icon,color:AppColors.blue,size:13),Text(label,style:const TextStyle(fontSize:6.5,color:AppColors.secondary)),Text(value,style:const TextStyle(fontSize:7.5,fontWeight:FontWeight.w700))]);}
