name: dondonhae
description: 돈돈해 모바일 대시보드
publish_to: none
version: 1.1.1+2
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  http: ^1.2.2
  shared_preferences: ^2.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/pig_hero.jpg
    - assets/data/pig-price.json
    - assets/data/pig-price-history.json
    - assets/data/platform.json
