import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../data/benefit_repository.dart';
import '../services/data_refresh_service.dart';
import '../models/benefit_models.dart';
import '../settings/farm_location_settings.dart';
import '../theme/app_theme.dart';
import '../widgets/farm_location_picker.dart';

enum _Period{open,upcoming,unknown,closed}
class _Category{const _Category(this.name,this.icon,this.pattern);final String name;final IconData icon;final RegExp? pattern;}

class BenefitPage extends StatefulWidget{const BenefitPage({super.key});@override State<BenefitPage> createState()=>_BenefitPageState();}
class _BenefitPageState extends State<BenefitPage>{
 final _repository=BenefitRepository();BenefitFeed? _feed;bool _loading=false;int category=0;_Period period=_Period.open;
 final categories=< _Category>[
  _Category('전체',Icons.grid_view_rounded,null),_Category('시설·장비',Icons.account_tree_outlined,RegExp(r'시설|장비|ICT|환기|스마트')),_Category('방역·질병',Icons.health_and_safety_outlined,RegExp(r'방역|질병|소독|구제역|ASF|PED|PRRS')),_Category('환경·저탄소',Icons.eco_outlined,RegExp(r'환경|저탄소|분뇨|악취|질소|에너지')),_Category('사료·사양',Icons.scale_outlined,RegExp(r'사료|사양|종축|가축')),_Category('교육·컨설팅',Icons.school_outlined,RegExp(r'교육|컨설팅|청년|경영')),
 ];
 @override void initState(){super.initState();FarmLocationSettings.instance.addListener(_locationChanged);DataRefreshService.revision.addListener(_updated);_load();}
 @override void dispose(){FarmLocationSettings.instance.removeListener(_locationChanged);DataRefreshService.revision.removeListener(_updated);super.dispose();}
 Future<void> _updated()async{final feed=await _repository.cached();if(mounted)setState(()=>_feed=feed);}
 void _locationChanged(){if(mounted)setState((){});}
 Future<void> _load()async{try{final c=await _repository.cached();if(mounted)setState(()=>_feed=c);}catch(_){}await _refresh();}
 Future<void> _refresh()async{if(_loading)return;setState(()=>_loading=true);try{final f=await _repository.refresh();if(mounted)setState(()=>_feed=f);}catch(_){}finally{if(mounted)setState(()=>_loading=false);}}
 bool _region(BenefitNotice x,FarmLocation l)=>x.region.isEmpty||x.region.contains('전국')||(l.province.isNotEmpty&&x.region.contains(l.province))||(l.cityCounty.isNotEmpty&&x.region.contains(l.cityCounty))||(l.town.isNotEmpty&&x.region.contains(l.town));
 _Period _state(BenefitNotice x){final today=DateUtils.dateOnly(DateTime.now()),start=x.startDate==null?null:DateUtils.dateOnly(x.startDate!),end=x.deadline==null?null:DateUtils.dateOnly(x.deadline!);if(start==null&&end==null)return _Period.unknown;if(start!=null&&start.isAfter(today))return _Period.upcoming;if(end!=null&&end.isBefore(today))return _Period.closed;return _Period.open;}
 List<BenefitNotice> get _items{final l=FarmLocationSettings.instance.location,c=categories[category];final rows=(_feed?.items??const<BenefitNotice>[]).where((x)=>_region(x,l)&&_state(x)==period&&(c.pattern==null||c.pattern!.hasMatch(x.title))).toList();rows.sort((a,b)=>(a.deadline??DateTime(2100)).compareTo(b.deadline??DateTime(2100)));return rows;}
 @override Widget build(BuildContext context){final location=FarmLocationSettings.instance.location,items=_items;return Scaffold(backgroundColor:AppColors.background,appBar:AppBar(toolbarHeight:70,backgroundColor:Colors.transparent,centerTitle:true,leading:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_ios_new_rounded)),title:const Column(children:[Text('내 지역 지원사업',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),SizedBox(height:2),Text('내 농장 지역의 최신 공식 지원사업을 한눈에 확인하세요.',style:TextStyle(fontSize:10.5,color:AppColors.secondary,fontWeight:FontWeight.w600))]),actions:[IconButton(tooltip:'공식 공고 새로고침',onPressed:_refresh,icon:const Icon(Icons.refresh_rounded)) ]),body:RefreshIndicator(onRefresh:_refresh,color:AppColors.coral,child:ListView(padding:const EdgeInsets.fromLTRB(14,5,14,28),children:[
  _hero(location),const SizedBox(height:12),_categoryTabs(),const SizedBox(height:12),_periodTabs(),if(_loading)...[const SizedBox(height:8),const LinearProgressIndicator(minHeight:2,color:AppColors.coral)],const SizedBox(height:10),
  if(items.isEmpty)_empty(location) else ...items.map(_card),const SizedBox(height:12),_guide(),const SizedBox(height:12),SizedBox(height:46,child:OutlinedButton.icon(onPressed:_refresh,style:OutlinedButton.styleFrom(side:const BorderSide(color:AppColors.coral),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22))),icon:const Icon(Icons.refresh_rounded),label:const Text('공식 공고 새로고침',style:TextStyle(fontWeight:FontWeight.w900))))
 ])));
 }
 Widget _hero(FarmLocation l)=>Container(height:124,padding:const EdgeInsets.fromLTRB(15,12,12,12),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFFF7F9),Color(0xFFFFE7EE)]),borderRadius:BorderRadius.circular(22),border:Border.all(color:const Color(0xFFFFE1E9))),child:Row(children:[const CircleAvatar(radius:26,backgroundColor:Colors.white,child:Icon(Icons.location_on_rounded,size:31,color:AppColors.coral)),const SizedBox(width:12),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('내 지역',style:TextStyle(fontSize:10.5,color:AppColors.secondary,fontWeight:FontWeight.w700)),const SizedBox(height:2),Text(l.label.isEmpty?'지역을 선택하세요':l.label,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900)),const SizedBox(height:8),Wrap(spacing:5,runSpacing:4,children:[if(l.province.isNotEmpty)_tag(l.province,true),if(l.cityCounty.isNotEmpty)_tag(l.cityCounty,false),if(l.town.isNotEmpty)_tag(l.town,false)])])),Column(mainAxisAlignment:MainAxisAlignment.center,children:[OutlinedButton.icon(onPressed:()async{await showFarmLocationPicker(context);},style:OutlinedButton.styleFrom(padding:const EdgeInsets.symmetric(horizontal:9),side:const BorderSide(color:AppColors.coral),shape:const StadiumBorder()),icon:const Icon(Icons.map_outlined,size:15),label:const Text('지역 변경',style:TextStyle(fontSize:10,fontWeight:FontWeight.w900))),const Row(mainAxisSize:MainAxisSize.min,children:[Text('🐷',style:TextStyle(fontSize:30)),Icon(Icons.campaign_rounded,size:26,color:AppColors.coral)])]) ]));
 Widget _tag(String s,bool active)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:4),decoration:BoxDecoration(color:active?AppColors.coral:Colors.white,borderRadius:BorderRadius.circular(7),border:Border.all(color:active?AppColors.coral:AppColors.divider)),child:Text(s,style:TextStyle(fontSize:9.5,fontWeight:FontWeight.w800,color:active?Colors.white:AppColors.secondary)));
 Widget _categoryTabs()=>SizedBox(height:78,child:ListView(scrollDirection:Axis.horizontal,children:categories.indexed.map((e){final selected=e.$1==category;return InkWell(onTap:()=>setState(()=>category=e.$1),borderRadius:BorderRadius.circular(13),child:Container(width:75,margin:const EdgeInsets.only(right:6),decoration:BoxDecoration(color:selected?AppColors.coral:Colors.white,borderRadius:BorderRadius.circular(13),boxShadow:const [BoxShadow(color:Color(0x0B000000),blurRadius:8)]),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(e.$2.icon,size:23,color:selected?Colors.white:const Color(0xFF85515E)),const SizedBox(height:3),Text(e.$2.name,textAlign:TextAlign.center,style:TextStyle(fontSize:9.5,fontWeight:FontWeight.w900,color:selected?Colors.white:AppColors.text))])));}).toList()));
 Widget _periodTabs(){final all=(_feed?.items??const<BenefitNotice>[]).where((x)=>_region(x,FarmLocationSettings.instance.location)).toList();int count(_Period p)=>all.where((x)=>_state(x)==p).length;return Row(children:[(_Period.open,'신청 가능'),(_Period.upcoming,'신청 예정'),(_Period.unknown,'기간 확인'),(_Period.closed,'종료')].map((x){final selected=period==x.$1;return Expanded(child:InkWell(onTap:()=>setState(()=>period=x.$1),child:Container(height:42,alignment:Alignment.center,decoration:BoxDecoration(color:selected?AppColors.coral:Colors.transparent,borderRadius:BorderRadius.circular(12)),child:FittedBox(fit:BoxFit.scaleDown,child:Text('${x.$2} (${count(x.$1)})',style:TextStyle(fontSize:9.5,fontWeight:FontWeight.w900,color:selected?Colors.white:AppColors.secondary))))));}).toList());}
 Widget _empty(FarmLocation l)=>Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:18,vertical:34),decoration:appCard(radius:20),child:Column(children:[const Icon(Icons.campaign_outlined,size:39,color:AppColors.secondary),const SizedBox(height:12),Text((_feed?.status.contains('키 연결 대기')??false)?'지원사업 API 연결이 필요합니다.':'선택한 조건에 표시할 공식 공고가 없습니다.',textAlign:TextAlign.center,style:TextStyle(fontSize:14,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('${l.label}에 맞는 공고가 확인되면\n이곳에 표시합니다.\n임의의 사업이나 지원금액은 표시하지 않습니다.',textAlign:TextAlign.center,style:const TextStyle(fontSize:10.5,height:1.55,color:AppColors.secondary,fontWeight:FontWeight.w600))]));
 Widget _card(BenefitNotice x){final c=categories.skip(1).firstWhere((c)=>c.pattern!.hasMatch(x.title),orElse:()=>categories[1]);final end=x.deadline;final d=end?.difference(DateUtils.dateOnly(DateTime.now())).inDays;final state=_state(x);final badge=state==_Period.upcoming?'신청 예정':state==_Period.unknown?'기간 확인':state==_Period.closed?'종료':d==0?'오늘 마감':'마감 D-${d??0}';return InkWell(onTap:()async{final u=Uri.tryParse(x.url);if(u!=null)await launchUrl(u,mode:LaunchMode.externalApplication);},borderRadius:BorderRadius.circular(18),child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(12),decoration:appCard(radius:18),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:70,height:82,decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFFDCE6),Color(0xFFFFF6F8)],begin:Alignment.topLeft,end:Alignment.bottomRight),borderRadius:BorderRadius.circular(12)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(c.icon,size:29,color:AppColors.coral),const SizedBox(height:5),Text(badge,style:const TextStyle(fontSize:8.5,color:AppColors.coral,fontWeight:FontWeight.w900))])),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.title,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:12.5,height:1.3,fontWeight:FontWeight.w900)),const SizedBox(height:5),Wrap(spacing:4,runSpacing:4,children:[_smallTag(x.region),_smallTag(c.name)]),const SizedBox(height:7),Text(x.target,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:9.5,color:AppColors.secondary,fontWeight:FontWeight.w600))])),const SizedBox(width:7),SizedBox(width:102,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('🗓  신청기간',style:TextStyle(fontSize:9,color:AppColors.secondary,fontWeight:FontWeight.w700)),const SizedBox(height:3),Text(end==null?'기간 확인 필요':'~ ${_date(end)}',style:const TextStyle(fontSize:9.5,color:AppColors.coral,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('📋  지원내용',style:TextStyle(fontSize:9,color:AppColors.secondary,fontWeight:FontWeight.w700)),const SizedBox(height:3),Text(x.support,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:9.5,fontWeight:FontWeight.w800)),const Align(alignment:Alignment.centerRight,child:Icon(Icons.chevron_right_rounded,size:18,color:AppColors.coral))])) ])));}
 Widget _smallTag(String s)=>Container(padding:const EdgeInsets.symmetric(horizontal:6,vertical:2),decoration:BoxDecoration(borderRadius:BorderRadius.circular(5),border:Border.all(color:const Color(0xFFE8D6DB))),child:Text(s,style:const TextStyle(fontSize:8.5,color:AppColors.secondary,fontWeight:FontWeight.w700)));
 String _date(DateTime d)=>'${d.year}.${d.month.toString().padLeft(2,'0')}.${d.day.toString().padLeft(2,'0')}';
 Widget _guide()=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFFFF1F5),borderRadius:BorderRadius.circular(18)),child:const Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.lightbulb_rounded,color:AppColors.coral),SizedBox(width:10),Expanded(child:Text('안내\n· 지자체·정부·공공기관의 공식 공고만 제공합니다.\n· 세부 내용은 공고 원문을 반드시 확인해주세요.\n· 임의의 사업이나 지원금액은 표시하지 않습니다.',style:TextStyle(fontSize:10,height:1.55,fontWeight:FontWeight.w600)))]));
}
