import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../data/disease_repository.dart';
import '../models/disease_models.dart';
import '../theme/app_theme.dart';
import '../widgets/korea_disease_map.dart';
import '../settings/farm_location_settings.dart';
import '../services/notification_service.dart';
import 'section_pages.dart';

class DiseasePage extends StatefulWidget{const DiseasePage({super.key});@override State<DiseasePage> createState()=>_DiseasePageState();}
class _DiseasePageState extends State<DiseasePage>{
  final _repository=DiseaseRepository();DiseaseFeed? _feed;int _tab=0;double? _lat,_lng;bool _gpsVerified=false;String? _message;
  @override void initState(){super.initState();FarmLocationSettings.instance.addListener(_syncLocation);_loadLocation();_load();}
  @override void dispose(){FarmLocationSettings.instance.removeListener(_syncLocation);super.dispose();}
  Future<void> _loadLocation()async{await FarmLocationSettings.instance.load();_syncLocation();}
  void _syncLocation(){final x=FarmLocationSettings.instance.location;if(mounted)setState((){_lat=x.latitude;_lng=x.longitude;_gpsVerified=x.gpsVerified;});}
  Future<void> _load()async{try{final cached=await _repository.cached();if(mounted)setState(()=>_feed=cached);}catch(_){}await _refresh();}
  Future<void> _refresh()async{try{final previous=(_feed?.items??const <DiseaseAlert>[]).map((x)=>x.stableKey).toSet();final value=await _repository.refresh();if(previous.isNotEmpty){for(final item in value.items.where((x)=>x.scope=='국내'&&x.isOfficial&&!previous.contains(x.stableKey))){await NotificationService.instance.newDisease(item.disease,item.region??'국내');}}if(mounted)setState(()=>_feed=value);}catch(_){if(mounted)setState(()=>_message='통신이 원활하지 않아 마지막 저장 정보를 표시합니다.');}}
  List<DiseaseAlert> get _items=>(_feed?.items??const []).where((x)=>x.scope==(_tab==0?'국내':'국외')).toList();
  @override Widget build(BuildContext context)=>PageShell(title:'질병 정보',subtitle:'가축질병 상황을 빠르게 확인하세요',child:Column(children:[
    _tabs(),const SizedBox(height:10),_counts(),const SizedBox(height:10),
    if(_message!=null)Container(width:double.infinity,margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:AppColors.lightCoral,borderRadius:BorderRadius.circular(11)),child:Text(_message!,style:const TextStyle(fontSize:9.5,color:AppColors.coral))),
    if(_tab==0)KoreaDiseaseMap(items:_items,onTap:_detail,userLatitude:_lat,userLongitude:_lng)
    else Container(width:double.infinity,padding:const EdgeInsets.all(14),decoration:appCard(radius:16),child:const Row(children:[Icon(Icons.public,color:AppColors.blue),SizedBox(width:9),Expanded(child:Text('해외 정보는 국가가 확인된 항목만 표시합니다.\n해외 발생을 국내 지도에 표시하지 않습니다.',style:TextStyle(fontSize:10.5,height:1.45)))])),
    const SizedBox(height:12),Row(children:[const Expanded(child:Text('최근 발생 현황',style:TextStyle(fontSize:14,fontWeight:FontWeight.w900))),TextButton(onPressed:_refresh,child:const Text('더보기  ›',style:TextStyle(fontSize:10,color:AppColors.coral,fontWeight:FontWeight.w800)))]),
    if(_items.isEmpty)const Padding(padding:EdgeInsets.symmetric(vertical:30),child:Text('현재 확인된 항목이 없습니다.\n새로운 공식 발표가 확인되면 업데이트합니다.',textAlign:TextAlign.center,style:TextStyle(fontSize:11,height:1.5,color:AppColors.secondary)))
    else ..._items.take(12).map(_row),
  ]));
  Widget _tabs()=>Container(height:38,padding:const EdgeInsets.all(3),decoration:BoxDecoration(color:const Color(0xFFF4F4F6),borderRadius:BorderRadius.circular(16)),child:Row(children:List.generate(2,(i)=>Expanded(child:InkWell(onTap:()=>setState(()=>_tab=i),child:Container(alignment:Alignment.center,decoration:BoxDecoration(color:_tab==i?AppColors.coral:Colors.transparent,borderRadius:BorderRadius.circular(13)),child:Text(i==0?'국내':'해외',style:TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:_tab==i?Colors.white:AppColors.secondary))))))));
  Widget _counts(){final names=['ASF','구제역','PED','PRRS'];int count(String name)=>_items.where((x)=>x.disease==name&&x.isOfficial).length;Widget pair(int start)=>Expanded(child:Container(height:42,margin:EdgeInsets.only(right:start==0?5:0,left:start==0?0:5),padding:const EdgeInsets.symmetric(horizontal:8),decoration:BoxDecoration(color:const Color(0xFFF7F7F9),borderRadius:BorderRadius.circular(15)),child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[for(var i=start;i<start+2;i++)Row(mainAxisSize:MainAxisSize.min,children:[Text(names[i],style:TextStyle(fontSize:10,fontWeight:FontWeight.w900,color:i==1?const Color(0xFF4B4F59):AppColors.coral)),const SizedBox(width:4),CircleAvatar(radius:10,backgroundColor:count(names[i])>0?AppColors.coral:Colors.white,child:Text('${count(names[i])}',style:TextStyle(fontSize:8,fontWeight:FontWeight.w900,color:count(names[i])>0?Colors.white:AppColors.secondary)))])])));return Row(children:[pair(0),pair(2)]);}
  Widget _row(DiseaseAlert x){final distance=_distance(x);final place=x.region??(x.countryCode.isEmpty?x.scope:x.countryCode);return InkWell(onTap:()=>_detail(x),child:Container(height:43,decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:AppColors.divider))),child:Row(children:[const Icon(Icons.control_point_duplicate,size:13,color:Color(0xFF5D6A80)),const SizedBox(width:7),SizedBox(width:42,child:Text(x.disease,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900,color:AppColors.coral))),Expanded(child:Text(place,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:9.5,color:AppColors.secondary))),Text(_date(x.publishedAt).replaceAll('-','.'),style:const TextStyle(fontSize:8.5,color:AppColors.secondary)),const SizedBox(width:8),Text(distance==null?'돼지':'${distance.toStringAsFixed(0)}km',style:const TextStyle(fontSize:8.5,color:AppColors.secondary))])));}
  void _detail(DiseaseAlert x)=>showModalBottomSheet(context:context,showDragHandle:true,isScrollControlled:true,builder:(context)=>SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(20,0,20,20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${x.disease} · ${x.scope}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(x.level,style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:x.isOfficial?AppColors.coral:const Color(0xFFB36A00))),const SizedBox(height:10),Text(x.summary,style:const TextStyle(fontSize:12,height:1.55)),const SizedBox(height:12),Text('지역: ${x.region??(x.scope=='국외'?x.countryCode:'지역 확인 중')}\n발표: ${_date(x.publishedAt)}\n출처: ${x.source}${_distance(x)==null?'':'\n설정 위치와 약 ${_distance(x)!.toStringAsFixed(0)}km'}',style:const TextStyle(fontSize:10.5,height:1.55,color:AppColors.secondary)),const SizedBox(height:14),SizedBox(width:double.infinity,height:46,child:FilledButton(onPressed:x.sourceUrl.isEmpty?null:()async{final uri=Uri.tryParse(x.sourceUrl);if(uri!=null)await launchUrl(uri,mode:LaunchMode.externalApplication);},style:FilledButton.styleFrom(backgroundColor:AppColors.coral),child:const Text('원문 확인'))),const SizedBox(height:8),const Text('공개정보·확인중 항목은 공식 확진으로 해석하지 마세요.',style:TextStyle(fontSize:9,color:AppColors.secondary))]))));
  double? _distance(DiseaseAlert x){if(!_gpsVerified||_lat==null||_lng==null||x.latitude==null||x.longitude==null)return null;const r=6371.0;final dLat=_rad(x.latitude!-_lat!),dLng=_rad(x.longitude!-_lng!);final a=math.sin(dLat/2)*math.sin(dLat/2)+math.cos(_rad(_lat!))*math.cos(_rad(x.latitude!))*math.sin(dLng/2)*math.sin(dLng/2);return r*2*math.atan2(math.sqrt(a),math.sqrt(1-a));}
  double _rad(double value)=>value*math.pi/180;
  String _date(String value)=>value.length>=10?value.substring(0,10):value;
}
