import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class PageShell extends StatelessWidget {
  const PageShell({super.key,required this.title,required this.subtitle,required this.child});
  final String title,subtitle; final Widget child;
  @override Widget build(BuildContext context)=>Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:CustomScrollView(slivers:[SliverPadding(padding:const EdgeInsets.fromLTRB(14,14,14,18),sliver:SliverList.list(children:[if(title.isNotEmpty) Text(title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),if(subtitle.isNotEmpty) Text(subtitle,style:const TextStyle(fontSize:11,color:AppColors.secondary)),if(title.isNotEmpty) const SizedBox(height:14),child]))])));
}

class MarketOverviewPage extends StatelessWidget { const MarketOverviewPage({super.key});
  @override Widget build(BuildContext context)=>PageShell(title:'시황',subtitle:'지금, 시장의 흐름을 한눈에',child:Column(children:[GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),mainAxisSpacing:10,crossAxisSpacing:10,childAspectRatio:1.38,children:const [_MarketTile('🐷','전국 돈가','6,442','원/kg','▼ 298원 (-4.42%)',false),_MarketTile('🌽','옥수수','301.2','\$/톤','▲ 2.4 (+0.8%)',true),_MarketTile('🫘','대두박','423.5','\$/톤','▲ 5.1 (+1.2%)',true),_MarketTile('＄','달러 환율','1,386','원','▲ 6 (+0.4%)',true)]),const SizedBox(height:10),const _MarketTile('🛢️','국제 유가 (WTI)','68.4','\$/배럴','▼ 1.2 (-1.7%)',false,wide:true),const SizedBox(height:18),const _SectionTitle('시황 요약 (오늘)'),const SizedBox(height:5),...['돈가|하락|전일 대비 298원 (-4.42%)','옥수수|상승|전일 대비 +0.8%','대두박|상승|전일 대비 +1.2%','환율|상승|전일 대비 +0.4%','유가|하락|전일 대비 -1.7%'].map((e){final p=e.split('|');return _SummaryRow(p[0],p[1],p[2]);})]));}
class _MarketTile extends StatelessWidget {const _MarketTile(this.emoji,this.name,this.value,this.unit,this.change,this.up,{this.wide=false});final String emoji,name,value,unit,change;final bool up,wide;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(13),decoration:appCard(radius:15),child:Row(children:[Text(emoji,style:TextStyle(fontSize:wide?30:25)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(name,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800)),RichText(text:TextSpan(style:const TextStyle(color:AppColors.text),children:[TextSpan(text:value,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900)),TextSpan(text:' $unit',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700))])),Text(change,style:TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:up?AppColors.coral:AppColors.blue))])),const Icon(Icons.chevron_right,color:AppColors.coral,size:18)]));}
class _SummaryRow extends StatelessWidget {const _SummaryRow(this.name,this.state,this.detail);final String name,state,detail;@override Widget build(BuildContext context)=>Container(height:40,decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:AppColors.divider))),child:Row(children:[SizedBox(width:58,child:Text(name,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700))),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:state=='상승'?AppColors.lightCoral:AppColors.lightBlue,borderRadius:BorderRadius.circular(12)),child:Text(state,style:TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:state=='상승'?AppColors.coral:AppColors.blue))),const SizedBox(width:10),Expanded(child:Text(detail,style:const TextStyle(fontSize:10,color:AppColors.secondary))) ]));}

class DiseasePage extends StatefulWidget {const DiseasePage({super.key});@override State<DiseasePage> createState()=>_DiseasePageState();}
class _DiseasePageState extends State<DiseasePage>{int tab=0;@override Widget build(BuildContext context)=>PageShell(title:'질병 정보',subtitle:'가축질병 상황을 빠르게 확인하세요',child:Column(children:[_Tabs(labels:const ['국내','해외'],index:tab,onTap:(i)=>setState(()=>tab=i)),const SizedBox(height:12),const Row(children:[Expanded(child:_Count('ASF','2')),Expanded(child:_Count('구제역','0')),Expanded(child:_Count('PED','1')),Expanded(child:_Count('PRRS','3'))]),const SizedBox(height:12),Container(height:285,decoration:appCard(radius:16),child:const Stack(children:[Center(child:Icon(Icons.map_outlined,size:210,color:Color(0xFFE5E6E9))),Positioned(left:110,top:70,child:Icon(Icons.circle,size:10,color:AppColors.coral)),Positioned(right:75,top:100,child:Icon(Icons.circle,size:10,color:AppColors.coral)),Positioned(right:55,top:180,child:Icon(Icons.circle,size:10,color:AppColors.coral)),Positioned(right:14,bottom:13,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('●  발생 지역',style:TextStyle(fontSize:10,color:AppColors.coral)),Text('●  내 위치',style:TextStyle(fontSize:10,color:AppColors.blue))]))])),const SizedBox(height:16),const _SectionTitle('최근 발생 현황'),...['ASF  |  경북 영주시  |  2025.09.15','PED  |  충남 논산시  |  2025.09.14','PRRS |  경기 이천시  |  2025.09.12','ASF  |  강원 철원군  |  2025.09.10'].map((x)=>Container(height:40,alignment:Alignment.centerLeft,decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:AppColors.divider))),child:Text(x,style:const TextStyle(fontSize:10.5))))])));}
class _Count extends StatelessWidget {const _Count(this.name,this.count);final String name,count;@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.symmetric(horizontal:2),padding:const EdgeInsets.symmetric(vertical:8),decoration:BoxDecoration(color:const Color(0xFFF8F8FA),borderRadius:BorderRadius.circular(12)),child:Text('$name  $count',textAlign:TextAlign.center,style:TextStyle(fontSize:9.5,fontWeight:FontWeight.w800,color:count=='0'?AppColors.secondary:AppColors.coral)));}

class FarmCheckPage extends StatefulWidget{const FarmCheckPage({super.key});@override State<FarmCheckPage> createState()=>_FarmCheckPageState();}
class _FarmCheckPageState extends State<FarmCheckPage>{int tab=0;final checks=List<bool>.filled(8,false);@override Widget build(BuildContext context)=>PageShell(title:'농장점검',subtitle:'오늘도 건강한 농장을 위해',child:Column(children:[_Tabs(labels:const ['분만사','자돈사','육성사','비육사'],index:tab,onTap:(i)=>setState(()=>tab=i)),const SizedBox(height:13),const Row(children:[Expanded(child:Text('점검 항목 (분만사)',style:TextStyle(fontSize:13,fontWeight:FontWeight.w900))),Text('2025.09.18 (목)',style:TextStyle(fontSize:9,color:AppColors.secondary))]),const SizedBox(height:5),...List.generate(checks.length,(i)=>_CheckRow(label:const ['온도 (적정 20~24℃)','환기 상태','급수 상태','급이 상태','돈방 상태','분뇨 상태','질병 이상 징후','폐사 두수'][i],checked:checks[i],onTap:()=>setState(()=>checks[i]=!checks[i]))),const SizedBox(height:10),TextField(maxLines:2,decoration:InputDecoration(hintText:'특이사항이 있으면 입력하세요.',hintStyle:const TextStyle(fontSize:10),filled:true,fillColor:const Color(0xFFF6F6F8),border:OutlineInputBorder(borderRadius:BorderRadius.circular(10),borderSide:BorderSide.none))),const SizedBox(height:10),SizedBox(width:double.infinity,height:44,child:FilledButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('점검 내용이 저장되었습니다.'))),style:FilledButton.styleFrom(backgroundColor:AppColors.coral),child:const Text('저장하기',style:TextStyle(fontWeight:FontWeight.w800)))),const SizedBox(height:16),const _SectionTitle('최근 점검 기록'),const _SummaryRow('9.17','분만사','이상 없음'),const _SummaryRow('9.16','자돈사','환기 점검 필요'),const _SummaryRow('9.15','비육사','이상 없음')])));}
class _CheckRow extends StatelessWidget{const _CheckRow({required this.label,required this.checked,required this.onTap});final String label;final bool checked;final VoidCallback onTap;@override Widget build(BuildContext context)=>InkWell(onTap:onTap,child:SizedBox(height:39,child:Row(children:[Icon(checked?Icons.check_box:Icons.check_box_outline_blank,color:checked?AppColors.coral:AppColors.secondary,size:20),const SizedBox(width:7),Expanded(child:Text(label,style:const TextStyle(fontSize:10.5))),Container(padding:const EdgeInsets.symmetric(horizontal:13,vertical:6),decoration:BoxDecoration(color:checked?AppColors.lightCoral:const Color(0xFFF4F4F6),borderRadius:BorderRadius.circular(12)),child:Text(checked?'양호':'확인',style:TextStyle(fontSize:9,color:checked?AppColors.coral:AppColors.secondary))) ])));}

class MorePage extends StatelessWidget{const MorePage({super.key});@override Widget build(BuildContext context)=>PageShell(title:'',subtitle:'',child:Column(children:[const ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(radius:24,backgroundColor:AppColors.lightCoral,child:Icon(Icons.person,color:Color(0xFF4B5A70))),title:Text('돈돈해님',style:TextStyle(fontSize:16,fontWeight:FontWeight.w900)),subtitle:Text('항상 감사합니다.',style:TextStyle(fontSize:10)),trailing:Icon(Icons.settings_outlined)),const Divider(),...const [('내 농장','등록된 농장 정보 관리',Icons.home_work_outlined),('인증 정보','깨끗한 축산농장 · 저탄소 · HACCP 등',Icons.health_and_safety_outlined),('정부·지자체 지원사업','내 지역 맞춤 지원사업 확인',Icons.account_balance_outlined),('알림 설정','돈가 · 질병 · 주문 · 지원사업 등',Icons.notifications_outlined),('지역 설정','내 지역: 대구 달성군',Icons.location_on_outlined),('데이터 출처','정보 제공 기관 안내',Icons.info_outline),('공지사항','앱 소식 및 업데이트',Icons.campaign_outlined),('이용약관 / 개인정보처리방침','',Icons.article_outlined),('앱 정보','버전 1.1.0',Icons.info)].map((x)=>ListTile(minTileHeight:57,contentPadding:EdgeInsets.zero,leading:Icon(x.$3,color:const Color(0xFF4B5A70),size:21),title:Text(x.$1,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800)),subtitle:x.$2.isEmpty?null:Text(x.$2,style:const TextStyle(fontSize:9,color:AppColors.secondary)),trailing:const Icon(Icons.chevron_right,size:18)))])));}

class _Tabs extends StatelessWidget{const _Tabs({required this.labels,required this.index,required this.onTap});final List<String> labels;final int index;final ValueChanged<int> onTap;@override Widget build(BuildContext context)=>Container(height:38,padding:const EdgeInsets.all(3),decoration:BoxDecoration(color:const Color(0xFFF4F4F6),borderRadius:BorderRadius.circular(16)),child:Row(children:List.generate(labels.length,(i)=>Expanded(child:InkWell(onTap:()=>onTap(i),child:Container(alignment:Alignment.center,decoration:BoxDecoration(color:i==index?AppColors.coral:Colors.transparent,borderRadius:BorderRadius.circular(13)),child:Text(labels[i],style:TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:i==index?Colors.white:AppColors.secondary))))))));}
class _SectionTitle extends StatelessWidget{const _SectionTitle(this.text);final String text;@override Widget build(BuildContext context)=>Align(alignment:Alignment.centerLeft,child:Text(text,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w900)));}
